config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "contexts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :contexts, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end
  resources :looks, only: [:show]

  # Defines the root path route ("/")
  # root "posts#index"
  get "profile" => "pages#profile", as: :profile
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :context
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
  @context = Context.find(params[:context_id])
  @message = Message.new(message_params)
  @message.role = "user"
  @message.context = @context
  objective = @message.context["objective"]
  morphology = @message.context.user["morphology"]
  instructions = "You are a professional personal shopper.
              Your role is to help a client choose looks that best match their needs.
              The client wants a style adapted to its objective (#{objective}) and morphology (#{morphology}).
              3 styles were already suggested but do not fit client expectations.

              Task:
              Generate a new different stylish looks based on the message he will send.

              For each look, provide:
              - a name
              - a short description explaining why it fits perfectly with the client. In order to attract customers who need quick solutions, it must be only one catchy sentence, as simple and effective as possible with the option of using until 2 targeted adjectives, in order to encourage clicks. This sentence should contain up to 20 words and shouldn't be displayed the name of the look.
              Do not list the individual clothing items.

              Output format:
              Return the result as a JSON with a 'looks' that contains an array of 1 object.
              Each object must have two fields: 'name' and 'description'.
              Do not include extra text before or after the JSON."

    if @message.save
      response = RubyLLM.chat.with_instructions(instructions).ask(@message.content)
      looks_payload = JSON.parse(response.content)["looks"]
      looks_payload = looks_payload[0]
      @look = Look.create!(description: looks_payload["description"], name: looks_payload["name"], context: @context)
      # redirect_to context_path(@context)
      respond_to do |format|
          format.turbo_stream # renders `app/views/messages/create.turbo_stream.erb`
          format.html { redirect_to context_path(@context) }
        end
    else
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace("new_message", partial: "messages/form", locals: { context: @context, message: @looks }) }
        format.html { render "contexts/show", status: :unprocessable_entity }
      end
    # else
    #   render "chats/show"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

  # def create_looks(array)
  #   array.map do |element|
  #     Look.create!(description: element["description"], name: element["name"], context: @context)
  #   end
  # end

end

app/views/messages/_form.html.erb
<%= simple_form_for [context, message] do |f| %>
      <%= f.input :content,
                  placeholder: "Not 100% satisfied by Vestiary suggestions?",
                  required: true,
                  label: false,
                  as: :text,
                  input_html: { class: "border rounded-4 bg-white shadow-sm mb-4 text-secondary", rows: 3 } %>

      <%= f.button :submit, "Fine tune my research",
          class: "btn btn-dark btn-lg w-100 shadow" %>
        <% end %>

app/views/messages/_message.html.erb
<%
        require 'open-uri'
        api_key = ENV["UNSPLASH_API_KEY"]
         url = "https://api.unsplash.com/search/photos?client_id=#{api_key}&page=1&query=#{look.name}"
         image_serialized = URI.parse(url).read
         image = JSON.parse(image_serialized)
         image_link = image["results"][0]["urls"]["small"] %>
        <div class="border rounded-4 bg-white flex-shrink-0 m-3 mb-3 d-flex align-content-between flex-wrap shadow-sm" style="width: 550px;">
          <div class="d-flex w-100 rounded-4">
            <div class="rounded-start-4" style="background-image:url('<%= image["results"][0]["urls"]["small"]%>');width: 300px; height: 320px; background-size: cover; background-position:center;"></div>
            <div class="w-75 d-flex align-content-between flex-wrap px-3">
              <div>
                <h4 class="mt-3"><%= look.name %></h4>
                <p><%= look.description %></p>
              </div>
            <%= link_to "SEE SUGGESTIONS", look_path(look), class: "text-dark text-decoration-none see-result mb-3" %>
            </div>
          <%# /contexts/:context_id/looks/:id(.:format) %>
          </div>
        </div>

app/views/messages/_messages.html.erb
<% looks.order(created_at: :desc).each do |look| %>
  <%= render "messages/message", look: look %>
  <% end %>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.prepend "messages" do %>
  <%= render "messages/message", look: @look %>
<% end %>

<%= turbo_stream.update "new_message" do %>
  <%= render "messages/form", context: @context, message: Message.new %>
<% end %>